### PR TITLE
Adjust to Nemo changes

### PR DESCRIPTION
**Pull request by joschmitt**
I expected this to be more complicated... This should make Hecke ready for Nemo 0.43.1.

### CODE REVIEW

**Comment by fingolfin** [comment]
There are doctest failures, though, due to some doctest code now resulting in errors.

**Comment by joschmitt** [comment]
> There are doctest failures, though, due to some doctest code now resulting in errors.

Yes, all the failures are expected, this needs Nemo 0.43.1 now.
(The "cleanest" thing would have been to first release Nemo and then use the `SolveCtx` stuff in Hecke, but it is too late for this.)

**Comment by joschmitt** [comment]
Closing this now. Can/needs to be done in one go when we get #1413 back in.

**Comment by thofma** [comment]
When we revert the revert, we can cherry-pick it.

**Pull request closed without merging**
