### PR TITLE
Add `Aqua.jl` for some static testing

### PR DESCRIPTION
**Pull request by lgoettgens**
See https://github.com/oscar-system/Oscar.jl/issues/2385.

### CODE REVIEW

**Comment by thofma** [comment]
Hm, tests are failing

**Comment by lgoettgens** [comment]
Aqua seems to be unhappy that for testing GAP and Polymake are being loaded, although they are no dependencies.
I suggest adding them to the ignore section of the Aqua config.

**Comment by thofma** [comment]
I guess we are hitting https://github.com/JuliaTesting/Aqua.jl/pull/130?

**Comment by lgoettgens** [comment]
> I guess we are hitting [JuliaTesting/Aqua.jl#130](https://github.com/JuliaTesting/Aqua.jl/pull/130)?

Exactly. I hope Max will merge and release that soon-ish to then continue here.

**Comment by lgoettgens** [comment]
> I guess we are hitting [JuliaTesting/Aqua.jl#130](https://github.com/JuliaTesting/Aqua.jl/pull/130)?

https://github.com/JuliaTesting/Aqua.jl/pull/130 has now been released. So tests should succeed now.

**Comment by lgoettgens** [comment]
The occurring errors seem to be unrelated to the changes here.

**Comment by thofma** [comment]
Merci

**Pull request merged**
