### PR TITLE
Replace trailing_coefficient-> constant_coefficient. Remove definition of latter in preference for AA #806.

### PR DESCRIPTION
**Pull request by wbhart**
This is expected to fail until Hecke relies on a version of AA with https://github.com/Nemocas/AbstractAlgebra.jl/pull/806 merged.

### CODE REVIEW

**Comment by wbhart** [comment]
I have not yet checked if this will break Oscar.jl.

**Comment by wbhart** [comment]
Oscar should be fine with this. The trailing_coefficient function is not used there.

**Comment by wbhart** [comment]
I've also checked Hecke passes locally with these changes and that Singular does not use trailing_coefficient and so is unaffected by these PRs.

**Comment by wbhart** [comment]
@thofma You can merge this and https://github.com/Nemocas/AbstractAlgebra.jl/pull/806 together if you are happy with them. I have verified locally that they work together (though obviously not individually).

This is a prerequisite for the multivariate series, though please do not merge those until I review.

**Comment by thofma** [comment]
We first need a new AA version.

**Comment by wbhart** [comment]
That's fine. Do you want to merge all the other lead/trail/lt/lm/lc/coeffs/valence patches first then?

I am currently working on #805 to this end.

**Comment by thofma** [comment]
Yeah, that was basically my question in the AA PR. We can put all changes in today or whenever you have time to finish it and then tag a new release. Then adjust Nemo and then Hecke.

**Comment by wbhart** [comment]
Then you can merge https://github.com/Nemocas/AbstractAlgebra.jl/pull/806

May as well wait until 805 is in to prevent merge conflicts now though.

**Pull request closed without merging**
