### PR TITLE
fix Oscar #4170 - too low precision in factoring

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by thofma** [comment]
https://github.com/thofma/Hecke.jl/pull/1639 without the other commit

**Comment by thofma** [comment]
@fieker do you have the condensed example?

**Comment by fieker** [comment]
On Wed, Oct 09, 2024 at 03:08:16AM -0700, Tommy Hofmann wrote:
> @fieker do you have the condensed example?
Its still the degree 96 over quad. Don't know if we want to add it

**Comment by thofma** [comment]
The `NfAbs/Elem.jl` test finished, but they took 1700 seconds compared to 230 seconds without the changes here.

**Comment by fieker** [comment]
I checked out the th/facccc and it terminates on my machine in 150sec - now twice

**Comment by fieker** [comment]
OK, 13sec in the previous version. I see the problem

**Pull request merged**
