### PR TITLE
Use `padic_field`/`qadic_field` and prepare deprecations

### PR DESCRIPTION
**Pull request by joschmitt**
The "trivial" part of #1522.

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Excellent!

**Comment by lgoettgens** [comment]
@thofma I think it would make sense to get this merged before doing the heavy work in Nemo that then needs https://github.com/thofma/Hecke.jl/pull/1522.

**Comment by joschmitt** [comment]
Nothing should need #1522. I think you mean #1605.

**Comment by lgoettgens** [comment]
> Nothing should need #1522. I think you mean #1605.

Yes, exactly. Thanks for pointing this out.

**Pull request closed without merging**
