### PR TITLE
Fix issue #1018

### PR DESCRIPTION
**Pull request by StevellM**
Fixes issue #1018 

There are many lines changes, mostly because I commented out around 800 lines of codes to reduce by almost a half the number of tests in `QuadForm/Quad/GenusRep.jl`.

### CODE REVIEW

**Comment by thofma** [comment]
I don't undestand. What is with the tests? If we don't need them for coverage, we should just remove them.

**Comment by StevellM** [comment]
We actually need some of them for correctness of the output, but we are testing too many examples, which makes the runtest rather slow on this file. I did not deleted the commented lines directly to see whether it was a reasonable removal (not having to remove, and the re-write later). If it looks fine, I can make a new commit with a proper deletion.

**Comment by thofma** [comment]
So with these disabled, we still have the same coverage. So can we remove them? Or does coverage not imply correctness?

**Comment by simonbrandhorst** [comment]
I think we added lots of test to spot any mathematical bugs. But now that we know it works, 
fewer tests seem good enough to spot regressions. And we still have the sanity check that the mass formula holds.
Therefore I am okay with removing the tests.

**Pull request merged**
