### PR TITLE
Replace Hecke's divisors() of Int and fmpz by Nemo's

### PR DESCRIPTION
**Pull request by albinahlback**
Divisors for fmpz and Int are (probably) going to be implemented in Nemo, and should therefore be removed in Hecke. I removed both divisors(::Int) and divisors(::fmpz), removed the export of it, and created an import of Nemo's divisors function.

The only function I see that implements these methods are `_d_find_rek!`. Before merging, make sure that this function does not depend on the output of `divisors` being ordered.

[Related pull request](https://github.com/Nemocas/Nemo.jl/pull/963).

### CODE REVIEW

**Comment by thofma** [comment]
Did you time the difference?

**Comment by thofma** [comment]
Sorry, I mean, did you compare the runtime of both versions?

**Comment by albinahlback** [comment]
> Sorry, I mean, did you compare the runtime of both versions?

Yes, I did. The new implementation appeared to be faster, wait a second and I will show you.

**Comment by albinahlback** [comment]
No wait, I'm sorry, they appear to be just as fast, while the new method makes more allocations.
```
julia> import Nemo

julia> import Hecke

julia> a = Nemo.ZZ(2^3 * 5 * 11^2 * 19 * 23)
2115080

julia> @time Nemo.divisors(a);
  0.005800 seconds (3.49 k allocations: 265.421 KiB)

julia> @time Nemo.divisors(a);
  0.000043 seconds (219 allocations: 9.359 KiB)

julia> @time Nemo.divisors(a);
  0.000026 seconds (219 allocations: 9.359 KiB)

julia> @time Nemo.divisors(a);
  0.000036 seconds (219 allocations: 9.359 KiB)

julia> @time Hecke.divisors0(a);
  0.490317 seconds (863.53 k allocations: 45.091 MiB, 14.15% gc time)

julia> @time Hecke.divisors0(a);
  0.000031 seconds (62 allocations: 4.406 KiB)

julia> @time Hecke.divisors0(a);
  0.000032 seconds (62 allocations: 4.406 KiB)

julia> @time Hecke.divisors0(a);
  0.000032 seconds (62 allocations: 4.406 KiB)
```

**Comment by albinahlback** [comment]
However, the methods for Int are faster, which I tested earlier.

**Comment by albinahlback** [comment]
Oh by the way, I renamed divisor to divisor0 in Hecke.

**Comment by thofma** [comment]
Thanks for checking. Yes, the `Int` version in Hecke was suboptimal. We will first have to make a new Nemo release, before we can merge this here (just to let you know).

**Comment by albinahlback** [comment]
I forgot to mention that the tests in Hecke with its and Nemo's proposed pull requests worked. I think I got one warning at the one of the last three includes (I think it was QuadForms), but no error.

**Comment by thofma** [comment]
I have rebased and will merge tomorrow once the lights turn green.

**Comment by albinahlback** [comment]
Let's hope they do!

**Comment by thofma** [comment]
Apart from the Windows tests which are allowed to fail, everything should be fine.

**Comment by thofma** [comment]
Thanks @albinahlback for the PR. Feel free to also open PRs where you want to add things to Hecke :wink:

**Comment by albinahlback** [comment]
Thank you! But don't expect much, I have a very limited formal training in pure mathematics that's not calculus.

However, I am hoping that my next academic year will be at Kaiserslautern, so maybe more in the future! :smile:

**Comment by thofma** [comment]
Sounds good.

**Pull request merged**
