### PR TITLE
Fix common_eigenspaces

### PR DESCRIPTION
**Pull request by joschmitt**
I needed common eigenspaces and noticed that Hecke has them (well hidden). Now they work again (`intersect_spaces` -> `_intersect_spaces`).
I decided that the default side for an eigenspace should be `:right` to be consistent with `kernel` (which is also an eigenspace after all).

### CODE REVIEW

**Comment by thofma** [comment]
This is Carlo land, so you can do whatever you want as long as the tests pass

**Comment by joschmitt** [comment]
Out of curiosity: how does this coverage get computed? My "diff coverage" is 100%, but overall it decreases?

**Comment by thofma** [comment]
See the discussion here: https://github.com/thofma/Hecke.jl/pull/592

**Comment by thofma** [comment]
@fieker Any comment since you looked at similar problems?

**Comment by fieker** [comment]
but the right/left is a catastrophy. We never implemented the default left stuff

**Pull request merged**
