### PR TITLE
Trivia

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by thofma** [comment]
Do you have the example for `prime_dec_gen`?

**Comment by fieker** [comment]
It's 5 and 29 in the corresponding pmax order of the splitting field of
quintic. But the splitting field is only nice to compute using Galois in
Oscar and this also unearthed problems...
The field is deg 120 with huge coeffs

**Comment by fieker** [comment]
In released oscar do
k,a = number_field(f)
G,S = galois_group(k, pStart=1000)
fixed_field(S, sub(G, [one(G)])[1])

And despair

**Comment by thofma** [comment]
Can you post the quintic?

**Comment by fieker** [comment]
-4*x^5 + 4*x^4 + 24*x^3 + 5*x^2 - 10*x + 5

**Comment by thofma** [comment]
I am not running into the problem that the minimum is not set.

I can reproduce the other error in the `anti_uniformizer` call.

**Comment by fieker** [comment]
I guess I ran into the minimum prob in the non prime_dec_gen path, that why
I also added the is maximal and know stuff to force it through the gen

**Pull request merged**
