### PR TITLE
degree 1 and 2 fields are difficult...

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by thofma** [comment]
Which bug does this fix? Do you have the example?

**Comment by fieker** [comment]
Tricky, an example would be
```K, a = cyclotomic_field(3)
L, b = cyclotomic_field(3)
Hecke.force_coerce_cyclo(L, a)
```
This possibly loops forever as `a.elem_length` is undefined, or crash or so. I can put a test in (trivial), but without the fix, the test may never terminate

**Comment by fieker** [comment]
even more difficult. Aparently, the element needs to be constructed in a bad way.

**Comment by thofma** [comment]
The don't bother adding the test.

**Comment by fieker** [comment]
On Mon, Nov 08, 2021 at 12:34:52AM -0800, Tommy Hofmann wrote:
> The don't bother adding the test.

Now I am curious as to why and where this element is coming from.
But there is a vague chance it was memory corruption elsewhere.

**Comment by thofma** [comment]
Merge at your own discretion.

**Pull request merged**
