### PR TITLE
Better hash for fmpz_mat

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by rfourquet** [comment]
Could this be done in `Nemo`?

**Comment by thofma** [comment]
For this it would be good to remove the one missing allocation.

**Comment by fieker** [comment]
hashing of fmpz is done in julia, hence there would be no problem in removing the allocation/ copying...

**Comment by fieker** [comment]
can't you just call hash(unsafe_pointer_to_objref(m)) without the fmpz_set?

**Comment by fieker** [comment]
OK, this works:
       m = ccall((:fmpz_mat_entry, libflint), Ptr{fmpz}, (Ref{fmpz_mat}, Int, Int), M, i - 1, j - 1)
        b = xor(b, xor(hash(unsafe_load(m), h), h))
and doesn't need ant fmpz_set or allocation

**Comment by fieker** [comment]
it allocates - why, I don't know (yet)

**Comment by fieker** [comment]
Sorry I am confused.
unsafe_load in hash -> hasing without allocation
in other applications -> allocations, but here, it seems fine and seems to solve the problem

**Comment by thofma** [comment]
Should call the "shiny new junk" here https://github.com/Nemocas/Nemo.jl/blob/master/src/flint/mpoly.jl#L67.

**Comment by fieker** [comment]
On Thu, Nov 18, 2021 at 03:18:41AM -0800, Tommy Hofmann wrote:
> Should call the "shiny new junk" here https://github.com/Nemocas/Nemo.jl/blob/master/src/flint/mpoly.jl#L67.
> 
Does not work directly. Views have no entries ptr - I learned this the
hard way...

**Comment by fieker** [comment]
yo'd need to call the new stuff on the rows array individually.

**Comment by thofma** [comment]
This is what he suggested.

**Pull request closed without merging**
