### PR TITLE
Allow singular matrices in `saturate`

### PR DESCRIPTION
**Pull request by mgkurtz**
Possible fix for #1101.

### CODE REVIEW

**Comment by fieker** [comment]
probably correct - but I'd expect it to be much slower (for suitable evil examples)
 - hnf_with_transform is much slower than hnf without
 - inv(T) is inverting a much larger matrix than inverting H - furthermore, H is square, upper triangular, so inverting is just writing it down. inv(T) is hard...

**Comment by mgkurtz** [comment]
I had some fun, adapting the original concept to the singular case. Indeed, the `hnf_with_transform` takes longer than the whole `saturate`. Curiously, for random input, inverting the unimodular transform U was faster than inverting the hnf matrix H. Probably, because (U⁻¹)ᵀ is the pretty looking result matrix, while the hnf and its inverse may have a few large entries.

**Comment by mgkurtz** [comment]
Hmph, I should listen better. You told me, not to compute the inverses, but to just solve the linear system directly. Well, this reduces the code to less than it was before, works out of the box for singular matrices, and speeds it up.

**Review by mgkurtz — COMMENTED** [review]
Just look at commit ea0b343 – unless you are interested in all the comments in the previous commits.

**Review by fieker — APPROVED** [review]

**Pull request merged**
