### PR TITLE
Remove outdated linear solving code

### PR DESCRIPTION
**Pull request by joschmitt**

### CODE REVIEW

**Comment by joschmitt** [comment]
> tests failing

Yeah, I'll try to fix it in the afternoon.

**Comment by joschmitt** [comment]
This is too arcane for me. This errors:
```
julia> E, b = cyclotomic_field_as_cm_extension(3);

julia> K = base_field(E);

julia> s = involution(E);

julia> Vh = hermitian_space(E, E[1 b 1; s(b) 4 s(b); 1 b 1]);

julia> @inferred Hecke._diagonal(Vh)
ERROR: return type Tuple{Vector{AbsSimpleNumFieldElem}, AbstractAlgebra.Generic.MatSpaceElem{Hecke.RelSimpleNumFieldElem{AbsSimpleNumFieldElem}}} does not match inferred return type Tuple{Vector{AbsSimpleNumFieldElem}, Any}
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ REPL[8]:1

julia> @inferred kernel(gram_matrix(Vh))
ERROR: return type AbstractAlgebra.Generic.MatSpaceElem{Hecke.RelSimpleNumFieldElem{AbsSimpleNumFieldElem}} does not match inferred return type Any
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ REPL[9]:1
```
But executing the commands in this order works (in a new session):
```
julia> E, b = cyclotomic_field_as_cm_extension(3);

julia> K = base_field(E);

julia> s = involution(E);

julia> Vh = hermitian_space(E, E[1 b 1; s(b) 4 s(b); 1 b 1]);

julia> @inferred kernel(gram_matrix(Vh))
[-1   0   1]

julia> @inferred Hecke._diagonal(Vh)
(AbsSimpleNumFieldElem[0, 4, 3//4], [-1 0 1; 0 1 0; 0 -1//4*z_3 1])
```
I tried using `@descend`, but it seems to by happy (or I'm using it wrong).

**Comment by thofma** [comment]
```
julia> @inferred kernel(E[0 0; 0 0])
ERROR: return type AbstractAlgebra.Generic.MatSpaceElem{Hecke.RelSimpleNumFieldElem{AbsSimpleNumFieldElem}} does not match inferred return type Any
Stacktrace:
```
This is already failing.

Can you check this PR here with https://github.com/Nemocas/AbstractAlgebra.jl/pull/1621?

**Comment by joschmitt** [comment]
> Can you check this PR here with [Nemocas/AbstractAlgebra.jl#1621](https://github.com/Nemocas/AbstractAlgebra.jl/pull/1621)?

Still fails unfortunately.

Oh, and this:
```
julia> E, b = cyclotomic_field_as_cm_extension(3);

julia> @inferred kernel(E[0 0; 0 0])
[1   0]
[0   1]
```
works. Just if one calls `Hecke._diagonal` first, it doesn't work any more.

**Comment by thofma** [comment]
I pushed a revision to the AA. Please try again.

**Comment by joschmitt** [comment]
Thank you! The example works now. I'll run the tests locally to see whether there is something else.

**Comment by joschmitt** [comment]
It works locally now.

**Pull request merged**
