### PR TITLE
make closure more restrictive

### PR DESCRIPTION
**Pull request by simonbrandhorst**
It was messing up some docstrings.

### CODE REVIEW

**Comment by fieker** [comment]
Will it kill Oscar? Closure is used in experimental/GModule/GModule.jl in finding minimal fields...

**Comment by thofma** [comment]
Are there tests for this in Oscar?

**Comment by simonbrandhorst** [comment]
I was hoping for the CI to tell me if it kills something :-). Since it is documented as `<: MatElem` the PR seemed natural.

**Comment by thofma** [comment]
@fieker Are there tests for this in Oscar?

**Comment by fieker** [comment]
On Sun, Apr 16, 2023 at 02:41:00AM -0700, Tommy Hofmann wrote:
> @fieker Are there tests for this in Oscar?

My guess is yes:
  l = irreducible_modules(AnticNumberField, small_group(48, 17),
  minimal_degree = true)
  l = irreducible_modules(AnticNumberField, small_group(48, 29),
  minimal_degree = true)

should/might touch the code

**Pull request merged**
