### PR TITLE
Try to sort out the homs

### PR DESCRIPTION
**Pull request by lgoettgens**
cf. https://github.com/oscar-system/Oscar.jl/pull/3667#issuecomment-2091079080

Alternative to and thus closes #1483.

### CODE REVIEW

**Comment by thofma** [comment]
why is Aqua unhappy?

**Comment by lgoettgens** [comment]
> why is Aqua unhappy?

The persistent task test does not work with deved dependecies

**Comment by thofma** [comment]
so just ignore it?

**Comment by lgoettgens** [comment]
Jup, should be fine. And even if not, we are not changing anything for oscar master here

**Pull request merged**
