### PR TITLE
Adjust to AbstractAlgebra

### PR DESCRIPTION
**Pull request by joschmitt**
Remove `howell_form` etc. Needs https://github.com/Nemocas/AbstractAlgebra.jl/pull/1738 .

### CODE REVIEW

**Comment by lgoettgens** [comment]
This needs to have https://github.com/thofma/Hecke.jl/pull/1562 merged first to get rid of some deprecation errors

**Comment by joschmitt** [comment]
There are more deprecation problems. I think I deprecated `is_power` in Nemo at some point; I'll look into it.

**Comment by lgoettgens** [comment]
> There are more deprecation problems. I think I deprecated `is_power` in Nemo at some point; I'll look into it.

This was part of https://github.com/Nemocas/Nemo.jl/pull/1771.

**Comment by joschmitt** [comment]
This seems to be fine now. I restarted one job which ran into #1526.

**Pull request merged**
