### PR TITLE
fix coefficient_ring call in trace / norm of qadics

### PR DESCRIPTION
**Pull request by alexjbest**
trace seems to be very broken to me, it gives random output (something is not being initialised properly? but norm looks like it works now)

### CODE REVIEW

**Comment by thofma** [comment]
Broken with or without this PR?

**Comment by alexjbest** [comment]
both, sorry! But with this PR the code runs at least and produces random output, rather than an error, and norm works with this PR

**Comment by thofma** [comment]
OK, can you provide the example? Thanks!

**Comment by alexjbest** [comment]
Is it possible I have somehow got a broken install? I just tried this on a different server and it works fine, yet on my laptop:

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Hecke

Welcome to Nemo version 0.16.2-dev

Nemo comes with absolutely no warranty whatsoever


Welcome to 

    _    _           _
   | |  | |         | |
   | |__| | ___  ___| | _____
   |  __  |/ _ \/ __| |/ / _ \
   | |  | |  __/ (__|   <  __/
   |_|  |_|\___|\___|_|\_\___|
    
Version 0.7.2-dev ... 
 ... which comes with absolutely no warranty whatsoever
(c) 2015-2019 by Claus Fieker, Tommy Hofmann and Carlo Sircana


julia> K = QadicField(73,3,7)
Unramified extension of 73-adic numbers of degree 3

julia> trace(K(2))
18 + 39*73^1 + 28*73^2 + 5*73^3 + O(73^7)

julia> trace(K(2))
6 + O(73^7)

julia> trace(K(2))
9 + 55*73^2 + 48*73^3 + 38*73^4 + 27*73^5 + 8*73^6 + O(73^7)

julia> trace(K(2))
Segmentation fault: 11


```

**Comment by thofma** [comment]
Weird, can you do a `Pkg.update()` and `Pkg.status()`? Then test again.

**Comment by alexjbest** [comment]
same result, both Hecke and Nemo on git master:

```

(v1.3) pkg> update
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
  [2edaba10] ↑ Nemo v0.16.1 [`~/.julia/dev/Nemo`] ⇒ v0.16.2 [`~/.julia/dev/Nemo`]
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [2edaba10] ↑ Nemo v0.16.1 [`~/.julia/dev/Nemo`] ⇒ v0.16.2 [`~/.julia/dev/Nemo`]

(v1.3) pkg> status
    Status `~/.julia/environments/v1.3/Project.toml`
  [c3fe647b] AbstractAlgebra v0.8.0 [`~/.julia/dev/AbstractAlgebra`]
  [18c793ea] Coleman v0.1.0 [`../../dev/Coleman`]
  [3e1990a7] Hecke v0.7.1 [`~/.julia/dev/Hecke`]
  [2edaba10] Nemo v0.16.2 [`~/.julia/dev/Nemo`]
  [c46f51b8] ProfileView v0.5.3
  [295af30f] Revise v2.5.0

(v1.3) pkg> 
+alex:~/.julia/dev/Hecke ((6f0a4d69...)) 🐌 julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Hecke
[ Info: Precompiling Hecke [3e1990a7-5d81-5526-99ce-9ba3ff248f21]

Welcome to Nemo version 0.16.3-dev

Nemo comes with absolutely no warranty whatsoever


Welcome to Nemo version 0.16.3-dev

Nemo comes with absolutely no warranty whatsoever


Welcome to 

    _    _           _
   | |  | |         | |
   | |__| | ___  ___| | _____
   |  __  |/ _ \/ __| |/ / _ \
   | |  | |  __/ (__|   <  __/
   |_|  |_|\___|\___|_|\_\___|
    
Version 0.7.2-dev ... 
 ... which comes with absolutely no warranty whatsoever
(c) 2015-2019 by Claus Fieker, Tommy Hofmann and Carlo Sircana


julia> K = QadicField(73,3,7)
Unramified extension of 73-adic numbers of degree 3

julia> trace(K(2))
61 + 24*73^1 + 13*73^2 + 21*73^3 + 7*73^4 + 51*73^5 + 16*73^6 + O(73^7)

julia> trace(K(2))
65 + 23*73^1 + 52*73^2 + 19*73^3 + 7*73^4 + 51*73^5 + 16*73^6 + O(73^7)
```

I also tried in flint2 the following script which I believe is the same thing. it looks like it works fine.
```
#include "qadic.h"

int main(void)
{
    fmpz_t p;
    slong d, N;
    qadic_ctx_t ctx;
    padic_ctx_t pctx;

    qadic_t a;
    padic_t b;

    /*************************************************************************/


    fmpz_init_set_ui(p, 83);
    d = 3;
    N = 7;
    qadic_ctx_init_conway(ctx, p, d, 0, N, "a", PADIC_SERIES);
    padic_ctx_init(pctx, p, 0, N, PADIC_SERIES);

    qadic_init2(a, N);
    padic_init2(b, N);

    flint_printf("Compute a trace\n");
    padic_poly_fit_length(a, 1);
    fmpz_one(a->coeffs + 0);
    fmpz_set_ui(a->coeffs + 0, 2);
    a->val = 0;
    _padic_poly_set_length(a, 1);

    qadic_print_pretty(a, ctx); flint_printf("\n");

    qadic_trace(b, a, ctx);
    padic_print(b, pctx); flint_printf("\n");

    qadic_clear(a);
    padic_clear(b);

    qadic_ctx_clear(ctx);
    fmpz_clear(p);


    return EXIT_SUCCESS;
}
```

**Pull request merged**
