### PR TITLE
Move function field code to FunField directory.

### PR DESCRIPTION
**Pull request by wbhart**
When I run the tests locally, this is what I get. Happens with both Julia-1.5 and Julia-1.6 and with current AbstractAlgebra master and Nemo master or with the new AbstractAlgebra generic_algorithms branch.

Am I doing something wrong here?

```
(@v1.6) pkg> test Hecke
     Testing Hecke
      Status `/tmp/jl_AjAwE6/Project.toml`
  [c3fe647b] AbstractAlgebra v0.17.1 `~/.julia/dev/AbstractAlgebra`
  [3e1990a7] Hecke v0.10.6 `~/.julia/dev/Hecke`
  [2edaba10] Nemo v0.23.1 `~/.julia/dev/Nemo`
  [fb686558] RandomExtensions v0.4.3
  [ae029012] Requires v1.1.3
  [ade2ca70] Dates `@stdlib/Dates`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [9abbd945] Profile `@stdlib/Profile`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_AjAwE6/Manifest.toml`
  [c3fe647b] AbstractAlgebra v0.17.1 `~/.julia/dev/AbstractAlgebra`
  [b99e7846] BinaryProvider v0.5.10
  [3e1990a7] Hecke v0.10.6 `~/.julia/dev/Hecke`
  [692b3bcd] JLLWrappers v1.3.0
  [472f376f] LoadFlint v0.5.1
  [2edaba10] Nemo v0.23.1 `~/.julia/dev/Nemo`
  [21216c6a] Preferences v1.2.2
  [fb686558] RandomExtensions v0.4.3
  [ae029012] Requires v1.1.3
  [e21ec000] Antic_jll v0.200.400+0
  [d9960996] Arb_jll v200.1900.1+0
  [fcfa6d1b] Calcium_jll v0.400.0+0
  [e134572f] FLINT_jll v200.700.100+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [9abbd945] Profile `@stdlib/Profile`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [781609d7] GMP_jll `@stdlib/GMP_jll`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [3a97d323] MPFR_jll `@stdlib/MPFR_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`
Precompiling project...
  3 dependencies successfully precompiled in 34 seconds (15 already precompiled)
     Testing Running tests...
using GAP failed.
[ Info: Hecke test setup
[ Info: long_test : false
[ Info: short_test: false
[ Info: parallel  : false
[ Info: tests     : ["QuadForm.jl", "AlgAss.jl", "AlgAssAbsOrd.jl", "AlgAssRelOrd.jl", "EllCrv.jl", "Examples.jl", "FunField.jl", "Grp.jl", "GrpAb.jl", "LinearAlgebra.jl", "LocalField.jl", "Map.jl", "Misc.jl", "NfAbs.jl", "NfOrd.jl", "NfRel.jl", "NumField.jl", "RCF.jl", "Sparse.jl"]
free(): invalid next size (fast)

signal (6): Aborted
in expression starting at /home/wbhart/.julia/dev/Hecke/test/QuadForm/Genus.jl:1
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fc3223203ed)
unknown function (ip: 0x7fc32232847b)
unknown function (ip: 0x7fc322329d2b)
jl_gc_counted_free_with_size at /buildworker/worker/package_linux64/build/src/gc.c:3387
fmpz_mat_clear at /home/wbhart/flint2/fmpz_mat/clear.c:22
fmpz_mat_mul at /home/wbhart/flint2/fmpz_mat/mul.c:130
mul! at /home/wbhart/.julia/dev/Nemo/src/flint/fmpz_mat.jl:1293 [inlined]
mul! at /home/wbhart/.julia/dev/Hecke/src/LinearAlgebra/FakeFmpqMat.jl:123
disclog at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:398
discrete_logarithm at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:553
_expand at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:358
#_iterative_method#1948 at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:296
_iterative_method##kw at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:267 [inlined]
#_iterative_method#1947 at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:263 [inlined]
_iterative_method at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:263 [inlined]
#_1_plus_p_mod_1_plus_pv#1946 at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:246
_1_plus_p_mod_1_plus_pv##kw at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:236 [inlined]
#_multgrp_mod_pv#1942 at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:134
_multgrp_mod_pv##kw at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:119 [inlined]
#_multgrp#1939 at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:85
_multgrp at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:68 [inlined]
_multgrp at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:68 [inlined]
multiplicative_group at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:25 [inlined]
unit_group at /home/wbhart/.julia/dev/Hecke/src/NfOrd/ResidueRingMultGrp.jl:35 [inlined]
LocMultGrpModSquMap at /home/wbhart/.julia/dev/Hecke/src/QuadForm/Quad/GenusRep.jl:1433
local_multiplicative_group_modulo_squares at /home/wbhart/.julia/dev/Hecke/src/QuadForm/Quad/GenusRep.jl:1512 [inlined]
spinor_norm at /home/wbhart/.julia/dev/Hecke/src/QuadForm/Quad/GenusRep.jl:270
_compute_ray_class_group at /home/wbhart/.julia/dev/Hecke/src/QuadForm/Quad/GenusRep.jl:813
SpinorGeneraCtx at /home/wbhart/.julia/dev/Hecke/src/QuadForm/Quad/GenusRep.jl:33
spinor_genera_in_genus at /home/wbhart/.julia/dev/Hecke/src/QuadForm/Quad/GenusRep.jl:157
#genus_representatives#3790 at /home/wbhart/.julia/dev/Hecke/src/QuadForm/Quad/GenusRep.jl:120
genus_representatives at /home/wbhart/.julia/dev/Hecke/src/QuadForm/Quad/GenusRep.jl:96
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:670
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:435
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:490
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:490
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:490
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:670
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
include_string at ./loading.jl:1094
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
_include at ./loading.jl:1148
include at ./client.jl:444
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:562
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:490
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:490
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:670
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
include_string at ./loading.jl:1094
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
_include at ./loading.jl:1148
include at ./client.jl:444
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
macro expansion at ./timing.jl:210 [inlined]
top-level scope at /home/wbhart/.julia/dev/Hecke/test/runtests.jl:172
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:871
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
include_string at ./loading.jl:1094
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
_include at ./loading.jl:1148
include at ./client.jl:444
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:562
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:670
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
exec_options at ./client.jl:261
_start at ./client.jl:485
jfptr__start_34289.clone_1 at /home/wbhart/julia-1.6.1/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:560
repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:702
main at /buildworker/worker/package_linux64/build/cli/loader_exe.c:51
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /home/wbhart/julia-1.6.1/bin/julia (unknown line)
Allocations: 716857842 (Pool: 716764797; Big: 93045); GC: 642
ERROR: Package Hecke errored during testing (received signal: 6)
```

### CODE REVIEW

**Comment by thofma** [comment]
Seems like you are using your local flint? Is this also 2.7.1?

**Comment by wbhart** [comment]
Yeah it should be 2.7.1 + fq_default patches. It possibly has some other stuff that was added to trunk after 2.7.1 as well.

Could that really be the issue? I'm not sure how to revert it now. How does one remove a jll?

**Comment by wbhart** [comment]
It's been like that a while too, and Hecke was passing against it no problems.

**Comment by wbhart** [comment]
I do get these warnings, which seem to be related to the ca_t stuff:

```
WARNING: could not import Nemo.isequal_root_order into Hecke
WARNING: could not import Nemo.isspecial into Hecke
```

**Comment by thofma** [comment]
CI is passing and I cannot reproduce it locally.

You are not using the `flint_jll` (it is loaded, but not used). How did you change it to use your local flint anyway? Are you using the override stuff?

**Comment by wbhart** [comment]
No, I just replaced the binary libflint.so. Anyhow, I deleted the relevant artifact directory and now that problem is gone. I don't know what is changed about the flint binary. We only deprecated stuff after that, I thought. Looks like someone made Flint incompatible with Hecke and didn't tell me what they did.

[OT] Hecke fails against #887, so I will try to figure out why. It complains about Wrong parents.

**Pull request merged**
