### PR TITLE
bump version number, in order to allow for GAP.jl 0.12

### PR DESCRIPTION
**Pull request by ThomasBreuer**
If Oscar.jl wants to use GAP.jl 0.12.0 then the Hecke.jl dependencies must allow GAP.jl 0.12 (see oscar-system/Oscar.jl/pull/4086).

### CODE REVIEW

**Comment by thofma** [comment]
This indeed needs adjustments. What is the substitute for `julia_to_gap`?

**Comment by ThomasBreuer** [comment]
One can call `GapObj` instead of `julia_to_gap`. I will adjust my pull request accordingly.
(Installing new methods for `GapObj` seems to be not needed in Hecke.jl.)

**Comment by thofma** [comment]
Found it in the meantime and pushed a fix.

**Comment by ThomasBreuer** [comment]
As far as I see, there is one more `GAP.julia_to_gap` call in `src/FieldFactory/CM_recognition.jl`.

**Comment by thofma** [comment]
thanks, I also missed another one

**Pull request merged**
