### PR TITLE
Global h2

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by thofma** [comment]
Sorry, but needs a rebase again.

**Comment by thofma** [comment]
Broken Oscar#master/h2 is expected?

**Comment by fieker** [comment]
On Fri, Mar 31, 2023 at 08:16:21AM -0700, Tommy Hofmann wrote:
> Broken Oscar#master/h2 is expected?
Oscar H2 needs Hecke H2... so, possibly yes?

**Comment by thofma** [comment]
I thought you aligned the two #GlobalH2 PRs

**Comment by fieker** [comment]
On Fri, Mar 31, 2023 at 08:19:15AM -0700, Tommy Hofmann wrote:
> I thought you aligned the two #GlobalH2 PRs
> 
They were - but I have no idea anymore. As far as I can see, the stuff
works locally... I shall have so much fun sorting

**Comment by fieker** [comment]
On Fri, Mar 31, 2023 at 08:19:15AM -0700, Tommy Hofmann wrote:
> I thought you aligned the two #GlobalH2 PRs
Bu the Oscar one definitely needs a Hecke with the PR in. As the Oscar
tests are using last release as far as I recall, they are goging to fail
at least until the next Hecke release. Then I can update the
Oscar-H2-Project file and hope...

Of course, by then at least Oscar will have changed further...

**Pull request merged**
