### PR TITLE
Sparse rref and kernel

### PR DESCRIPTION
**Pull request by joschmitt**
Here is a rref and kernel for sparse matrices. Sometimes they are faster than the regular ones...
I'm not sure what to return for the kernel: if we want to be consistent with the dense kernel, it would have to be a (sparse) matrix with the basis in the columns. But our sparse matrices are row based, so this would be pretty annoying to work with. So far I just return a vector of sparse rows. Or should one return a sparse matrix where the ROWS are the basis for the kernel (and document this)?
(This is also the reason why there is no `left_kernel` so far...)

### CODE REVIEW

**Comment by thofma** [comment]
Thanks! @fieker Any good idea about the return type?

**Comment by fieker** [comment]
On Fri, Jan 21, 2022 at 03:48:07AM -0800, Tommy Hofmann wrote:
> Thanks! @fieker Any good idea about the return type?
I think the kernel should be a dense matrix - as this is what it mainly
is.

**Comment by joschmitt** [comment]
> I think the kernel should be a dense matrix - as this is what it mainly is.

Good point, thanks!

**Comment by joschmitt** [comment]
Maybe don't merge this quite yet. I might have minor adjustments once I started using it.

**Comment by joschmitt** [comment]
This is good to go now.

**Comment by thofma** [comment]
The modules in Oscar use the sparse matrices, so the errors could be related?

**Comment by joschmitt** [comment]
> The modules in Oscar use the sparse matrices, so the errors could be related?

Oh, you're right. I'll have a look.

**Comment by joschmitt** [comment]
I think the problem was a missing deepcopy for `MPolyElem_dec`, see https://github.com/oscar-system/Oscar.jl/pull/1081 . Now the tests work for me locally.

**Comment by thofma** [comment]
@fieker Do you want to have a look? Otherwise I will merge soon.

**Pull request merged**
