### PR TITLE
Linear solving for p-adic residue rings

### PR DESCRIPTION
**Pull request by joschmitt**
Use the Howell form for linear solving over the new `LocalFieldValuationRingResidueRing`s.

The `kernel` method is copied from the `zzModMatrix` version in Nemo. I have no idea whether this is correct; it seems to work.

### CODE REVIEW

**Comment by joschmitt** [comment]
@simonbrandhorst does this help you in #1510?

**Comment by simonbrandhorst** [comment]
Thanks for contributing this! When I tried it I got the following error message:
```
ERROR: MethodError: no method matching ^(::Hecke.LocalFieldValuationRingResidueRingElem{Hecke.LocalField{…}, Hecke.LocalFieldElem{…}}, ::QQFieldElem)

Closest candidates are:
  ^(::RealFieldElem, ::QQFieldElem)
   @ Nemo ~/.julia/packages/Nemo/my7xb/src/arb/Real.jl:788
  ^(::RealFieldElem, ::QQFieldElem, ::Int64)
   @ Nemo ~/.julia/packages/Nemo/my7xb/src/arb/Real.jl:788
  ^(::ComplexFieldElem, ::QQFieldElem)
   @ Nemo ~/.julia/packages/Nemo/my7xb/src/arb/Complex.jl:315
  ...

Stacktrace:
  [1] annihilator(a::Hecke.LocalFieldValuationRingResidueRingElem{Hecke.LocalField{…}, Hecke.LocalFieldElem{…}})
    @ Hecke ~/.julia/dev/Hecke/src/LocalField/ResidueRing.jl:302
  [2] strong_echelon_form_naive!(A::AbstractAlgebra.Solve.LazyTransposeMatElem{…})
    @ Hecke ~/.julia/dev/Hecke/src/NumFieldOrd/NfOrd/StrongEchelonForm.jl:158
  [3] howell_form!(A::AbstractAlgebra.Solve.LazyTransposeMatElem{Hecke.LocalFieldValuationRingResidueRingElem{…}, AbstractAlgebra.Generic.MatSpaceElem{…}})
    @ Hecke ~/.julia/dev/Hecke/src/NumFieldOrd/NfOrd/StrongEchelonForm.jl:210
  [4] _can_solve_internal_no_check(A::AbstractAlgebra.Generic.MatSpaceElem{…}, b::AbstractAlgebra.Generic.MatSpaceElem{…}, task::Symbol; side::Symbol)
    @ Hecke ~/.julia/dev/Hecke/src/NumFieldOrd/NfOrd/StrongEchelonForm.jl:263
  [5] _can_solve_internal_no_check
    @ ~/.julia/dev/Hecke/src/NumFieldOrd/NfOrd/StrongEchelonForm.jl:246 [inlined]
  [6] _can_solve_internal(A::AbstractAlgebra.Generic.MatSpaceElem{…}, b::AbstractAlgebra.Generic.MatSpaceElem{…}, task::Symbol; side::Symbol)
    @ AbstractAlgebra.Solve ~/.julia/packages/AbstractAlgebra/dLVCE/src/Solve.jl:644
  [7] _can_solve_internal
    @ ~/.julia/packages/AbstractAlgebra/dLVCE/src/Solve.jl:636 [inlined]
  [8] #can_solve_with_solution#11
    @ ~/.julia/packages/AbstractAlgebra/dLVCE/src/Solve.jl:456 [inlined]
  [9] can_solve_with_solution
    @ ~/.julia/packages/AbstractAlgebra/dLVCE/src/Solve.jl:455 [inlined]
 [10] #solve#9
    @ ~/.julia/packages/AbstractAlgebra/dLVCE/src/Solve.jl:417 [inlined]
 [11] solve
    @ ~/.julia/packages/AbstractAlgebra/dLVCE/src/Solve.jl:416 [inlined]
```

The bug lies in ResidueRing.jl
```
function annihilator(a::LocalFieldValuationRingResidueRingElem)
  if is_zero(a)
    return one(parent(a))
  end
  pi = uniformizer(_valuation_ring(parent(a)))
  return parent(a)(pi)^(_exponent(parent(a)) - (valuation(data(a))))
end
```
the valuation seems to be a ``QQFieldElem``

**Comment by joschmitt** [comment]
This is fixed now. I should have tested with more obscure extensions, thanks for catching it!

**Comment by joschmitt** [comment]
From my side, this is good to go. I'm even convinced for the moment that the algorithm for the `kernel` is correct.

**Pull request merged**
