### PR TITLE
Fix and use some rank 2 code

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by thofma** [comment]
Are some of your examples degenerated, that is, zero discriminant?

**Comment by simonbrandhorst** [comment]
No, all non-degenerate.

**Comment by simonbrandhorst** [comment]
perhaps one of square determinant would be nice. They are all non-squares.

**Comment by thofma** [comment]
Yes, this is the case that was failing before. I will add one.

**Comment by simonbrandhorst** [comment]
There you go. Added some.

**Comment by simonbrandhorst** [comment]
square determinant and degenerate

**Comment by thofma** [comment]
Nice, thanks.

**Pull request merged**
