### PR TITLE
Change _zero_algebra -> zero_algebra

### PR DESCRIPTION
**Pull request by fingolfin**
The function _zero_algebra was renamed to zero_algebra some time ago, but not all places calling it were updated.

I found this because it caused a bunch of invalidations in code found while investigating #746 (indirectly, of course, as any actual call to `_zero_algebra` could not have worked).

### CODE REVIEW

**Comment by thofma** [comment]
Makes inference worse in some "unrelated" place, thus making the tests fail. (I have seen this happening before. I still don't know why.)

**Comment by lgoettgens** [comment]
Running these failing tests in the REPL does not fail, so this kind of weird to debug.

**Comment by fingolfin** [comment]
Here's a theory why: code which calls `_zero_algebra` by definition cannot work (because there is no `_zero_algebra`). LLVM may then classify this code as having UB (undefined behavior) and that enables many "optimizations" (basically you can replace calls to such code with anything). That in turn may make it possible to "prove" that certain functions are type stable, when they really are not.

If this guess is right, then anything that now fails inference should be checked as to whether it directly or indirectly leads to calls to `_zero_algebra`

**Comment by fingolfin** [comment]
I can reproduce this in the REPL:
```
julia> A = matrix_algebra(GF(2), 2)
Matrix algebra of dimension 4 over Prime field of characteristic 2

julia> @inferred Hecke._unit_group_generators(A)
ERROR: return type Vector{MatAlgebraElem{FqFieldElem, FqMatrix}} does not match inferred return type Any
```

This goes away if I change the last line of `Hecke._unit_group_generators` from `return map(A, res)` to `return res` or `return A, res`.

But `@code_warntype` reports nothing suspicious and indeed even displays the correct and concrete return type. Moreover, if I use the modified version with `return res`, and then do `@inferred map(A,res)` on the top level, there are no complaints...

Could this be a bug in `@inferred` then?!

**Comment by thofma** [comment]
Yeah, more (random) inference errors.

**Comment by fingolfin** [comment]
Fascinating. With this patch,
```
    E = elliptic_curve([1, 2, 3, 4, 5])
    a, b = @inferred CPS_height_bounds(E)
```
fails because inside `CPS_height_bounds` the return type of `CPS_dvev_real` can no longer be inferred. 

OK, I can reduce this to
```
    E = elliptic_curve([1, 2, 3, 4, 5])
    @inferred Hecke.CPS_dvev_real(E, PosInf(), 110)
```

There, it fails to infer the full return type for `Hecke._roots`. With this PR I see
```
│   %156 = Core.kwcall(%155, Hecke._roots, f, v)::Tuple{Vector{AcbFieldElem}, Any, Vector{AcbFieldElem}}
```
without the PR I see
```
│   %156 = Core.kwcall(%155, Hecke._roots, f, v)::Tuple{Vector{AcbFieldElem}, Vector{ArbFieldElem}, Vector{AcbFieldElem}}
```


Narrowing it down:
```
Kx, x = polynomial_ring(QQ, "x")
b2, b4, b6, b8 = (9, 11, 29, 35)
f = 4*x^3 + b2*x^2 + 2*b4*x + b6
@inferred Hecke._roots(f, PosInf(), prec = 110)
```

Will dig more later.

**Comment by lgoettgens** [comment]
I found a very simple example that differs between master and this branch:
```julia
julia> y = [AcbField(64)(1)]
1-element Vector{AcbFieldElem}:
 1.0000000000000000000

julia> @code_warntype real.(y)
MethodInstance for (::var"##dotfunction#234#8")(::Vector{AcbFieldElem})
  from (::var"##dotfunction#234#8")(x1) @ Main none:0
Arguments
  #self#::Core.Const(var"##dotfunction#234#8"())
  x1::Vector{AcbFieldElem}
Body::Any
1 ─ %1 = Base.broadcasted(Main.real, x1)::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(real), Tuple{Vector{AcbFieldElem}}}
│   %2 = Base.materialize(%1)::Any
└──      return %2
```
on this branch, while on master:
```julia
julia> @code_warntype real.(y)
MethodInstance for (::var"##dotfunction#225#1")(::Vector{AcbFieldElem})
  from (::var"##dotfunction#225#1")(x1) @ Main none:0
Arguments
  #self#::Core.Const(var"##dotfunction#225#1"())
  x1::Vector{AcbFieldElem}
Body::Vector{ArbFieldElem}
1 ─ %1 = Base.broadcasted(Main.real, x1)::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(real), Tuple{Vector{AcbFieldElem}}}
│   %2 = Base.materialize(%1)::Vector{ArbFieldElem}
└──      return %2
```

This then makes inference fail in https://github.com/thofma/Hecke.jl/blob/b3c226459fc2a6118c9de4c800d3e22ed98768bf/src/Misc/Poly.jl#L731 leading to the problems observed by @fingolfin

**Comment by fingolfin** [comment]
@lgoettgens thanks. Unfortunately that seems to be a dead end:
```julia
code_warntype(Base.materialize, (Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(real), Tuple{Vector{AcbFieldElem}}}, ))
```
prints perfectly inferred information in both branches.


I tried using `JET` but `@report_opt broadcast(real, y)` reports no issues (note that `@code_warntype broadcast(real, y)` shows the same behavior as your `@code_warntype real.(y)`

And according to `@descend broadcast(real, y)` everything is fine, too.


Aaargh!

**Comment by fingolfin** [comment]
Hah, I just tried with Julia 1.11.0-rc2 and there it works (both Lars example and also the elliptic curve example).

But it's not as if all was great: with that Julia, I get an inference failure with
```
g = @inferred supersingular_polynomial(2)
```
which works fine in Julia 1.10 (both with my branch and with master).


Seems we just can't have nice things *sigh*

**Pull request merged**
