### PR TITLE
Simplify some FinGenAbGroup function by using elementary_divisors

### PR DESCRIPTION
**Pull request by fingolfin**
Also fix `is_cyclic` for trivial `FinGenAbGroup`

### CODE REVIEW

**Comment by thofma** [comment]
Most of those should just call `elementary_divisors` I think. We probably did not have it back then.

**Comment by fingolfin** [comment]
I can use `elementary_divisors` if you prefer, but that will then lead to additional allocations as it does `return copy(G.snf)`

**Comment by thofma** [comment]
I think it is still worthwhile. The less we use `.snf` the better.

**Comment by fingolfin** [comment]
Is it guaranteed that there is no 1 in the vector returned by `elementary_divisors`? Its docstring doesn't really say so directly (well, I guess it must be implicitly true for the "uniqueness" claim to hold...)

**Comment by fingolfin** [comment]
Update to use `elementary_divisors` and I also tweaked the `elementary_divisors` docstring (to say that 1 does not occur, and to document that 0 may occur)

**Comment by thofma** [comment]
Thanks. Yeah, it is ambiguous about the `1`. I guess for elementary divisors of matrices, one probably includes the `1`, while for modules, one does not to make it unique.

**Pull request merged**
